// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentApi.Data.EfCodeFirst;

#nullable disable

namespace StudentApi.Data.EfCodeFirst.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentApi.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly?>("EnrolledOn")
                        .HasColumnType("date");

                    b.Property<string>("InternalNotes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RollNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RollNumber")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Students", t =>
                        {
                            t.HasCheckConstraint("CK_Students_Age", "Age BETWEEN 5 AND 100");

                            t.HasCheckConstraint("CK_Students_Score", "Score BETWEEN 0 AND 100");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 20,
                            Email = "asha.kumar@school.example",
                            EnrolledOn = new DateOnly(2026, 6, 1),
                            InternalNotes = "",
                            Name = "Asha Kumar",
                            RollNumber = "R001",
                            Score = 82,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Age = 21,
                            Email = "rohit.menon@school.example",
                            EnrolledOn = new DateOnly(2026, 6, 1),
                            InternalNotes = "",
                            Name = "Rohit Menon",
                            RollNumber = "R002",
                            Score = 64
                        },
                        new
                        {
                            Id = 3,
                            Age = 19,
                            Email = "divya.nair@school.example",
                            EnrolledOn = new DateOnly(2026, 6, 15),
                            InternalNotes = "Scholarship review pending",
                            Name = "Divya Nair",
                            RollNumber = "R003",
                            Score = 91
                        });
                });

            modelBuilder.Entity("StudentApi.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Designation = "Mathematics",
                            Email = "meera.iyer@school.example",
                            Name = "Meera Iyer",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Designation = "Physics",
                            Email = "arjun.rao@school.example",
                            Name = "Arjun Rao"
                        });
                });

            modelBuilder.Entity("StudentApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "Role IN ('Teacher', 'Student')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "PBKDF2-SHA256$100000$J0Zb75kU8S4WKblBDAMrYQ==$7o3+1kfT10l09ygTNfciYKy0t9ZQzlTN49koV4hImbQ=",
                            Role = "Teacher",
                            Username = "teacher1"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "PBKDF2-SHA256$100000$IvdcCNnm9IZEJ6iNMbW1fQ==$A8dqeb89Q4z+7vZRGjpEH3Iy+X46px+29wuxFOx3SZI=",
                            Role = "Student",
                            Username = "student1"
                        });
                });

            modelBuilder.Entity("StudentApi.Models.Student", b =>
                {
                    b.HasOne("StudentApi.Models.User", null)
                        .WithOne()
                        .HasForeignKey("StudentApi.Models.Student", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("StudentApi.Models.Teacher", b =>
                {
                    b.HasOne("StudentApi.Models.User", null)
                        .WithOne()
                        .HasForeignKey("StudentApi.Models.Teacher", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
