// Each call below LOOKS like it's calling a built-in instance method
// (e.g. `"hello world".ToTitleCase()`), but ToTitleCase/IsNullOrEmpty/
// ToWords are all custom extension methods we wrote ourselves in
// Extensions.cs - string, List<T>, and int weren't actually changed.
Console.WriteLine("string.ToTitleCase():");
Console.WriteLine($"  \"hello world\" -> \"{"hello world".ToTitleCase()}\"");

Console.WriteLine();
Console.WriteLine("List<T>.IsNullOrEmpty():");
List<int>? nullList = null;
List<int> emptyList = [];
List<int> filledList = [1, 2, 3];
Console.WriteLine($"  null list: {nullList.IsNullOrEmpty()}");
Console.WriteLine($"  empty list: {emptyList.IsNullOrEmpty()}");
Console.WriteLine($"  filled list: {filledList.IsNullOrEmpty()}");

Console.WriteLine();
Console.WriteLine("int.ToWords():");
foreach (var n in new[] { 0, 7, 19, 20, 45, 100, 305, 999 })
    Console.WriteLine($"  {n} -> {n.ToWords()}");

Console.WriteLine();
Console.WriteLine("Projecting Employee to anonymous { Name, AnnualSalary }:");
List<Employee> employees = [new("Asha", 7000), new("Rohit", 5500)];

// `new { e.Name, AnnualSalary = ... }` creates an ANONYMOUS TYPE - a
// throwaway object shape with no class name, generated by the compiler
// just for this spot in the code. It only works here because the compiler
// can see, right in this same method, exactly what shape `x` needs to be
// down in the foreach loop below.
var annualSalaries = employees.Select(e => new { e.Name, AnnualSalary = e.MonthlySalary * 12 });
foreach (var x in annualSalaries)
    Console.WriteLine($"  {x.Name}: {x.AnnualSalary:C}/yr");

// Here's the catch: you CANNOT pull that projection out into its own
// separate method, because an anonymous type has no name you're allowed to
// write down as a return type. There's simply no valid word to put where
// the "???" is below:
//
// public static ??? ProjectAnnualSalary(Employee e) => new { e.Name, AnnualSalary = e.MonthlySalary * 12 };
//
// Trying a made-up placeholder gives CS0246 ("type or namespace not
// found"); C# also won't let you write `var` as a method's return type.
// You COULD technically return it as `object` or `dynamic`, and that
// compiles - but then callers lose the ability to write `.Name` or
// `.AnnualSalary` with IntelliSense/compile-time checking, because as far
// as the compiler is concerned an `object` has no such properties. The
// real fix, if you need this shape outside one method, is to give it an
// actual name: a record (like Employee above) or a tuple such as
// (string Name, double AnnualSalary).
