// <auto-generated />
using System;
using Academics.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Academics.Api.Data.Migrations
{
    [DbContext(typeof(AcademicsDbContext))]
    [Migration("20261004101208_InitialAcademics")]
    partial class InitialAcademics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Academics.Api.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses", t =>
                        {
                            t.HasCheckConstraint("CK_Courses_Credits", "Credits BETWEEN 1 AND 10");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "MATH101",
                            Credits = 4,
                            TeacherId = 1,
                            Title = "Calculus I"
                        },
                        new
                        {
                            Id = 2,
                            Code = "PHYS101",
                            Credits = 4,
                            TeacherId = 2,
                            Title = "Mechanics"
                        },
                        new
                        {
                            Id = 3,
                            Code = "CS101",
                            Credits = 3,
                            Title = "Programming in C#"
                        });
                });

            modelBuilder.Entity("Academics.Api.Models.Enrollment", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EnrolledOn")
                        .HasColumnType("date");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            CourseId = 1,
                            EnrolledOn = new DateOnly(2026, 6, 2)
                        },
                        new
                        {
                            StudentId = 1,
                            CourseId = 3,
                            EnrolledOn = new DateOnly(2026, 6, 2)
                        },
                        new
                        {
                            StudentId = 2,
                            CourseId = 2,
                            EnrolledOn = new DateOnly(2026, 6, 3)
                        },
                        new
                        {
                            StudentId = 3,
                            CourseId = 1,
                            EnrolledOn = new DateOnly(2026, 6, 16)
                        });
                });

            modelBuilder.Entity("Academics.Api.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly?>("EnrolledOn")
                        .HasColumnType("date");

                    b.Property<string>("InternalNotes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RollNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RollNumber")
                        .IsUnique();

                    b.ToTable("Students", t =>
                        {
                            t.HasCheckConstraint("CK_Students_Age", "Age BETWEEN 5 AND 100");

                            t.HasCheckConstraint("CK_Students_Score", "Score BETWEEN 0 AND 100");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 20,
                            Email = "asha.kumar@school.example",
                            EnrolledOn = new DateOnly(2026, 6, 1),
                            InternalNotes = "",
                            Name = "Asha Kumar",
                            RollNumber = "R001",
                            Score = 82
                        },
                        new
                        {
                            Id = 2,
                            Age = 21,
                            Email = "rohit.menon@school.example",
                            EnrolledOn = new DateOnly(2026, 6, 1),
                            InternalNotes = "",
                            Name = "Rohit Menon",
                            RollNumber = "R002",
                            Score = 64
                        },
                        new
                        {
                            Id = 3,
                            Age = 19,
                            Email = "divya.nair@school.example",
                            EnrolledOn = new DateOnly(2026, 6, 15),
                            InternalNotes = "Scholarship review pending",
                            Name = "Divya Nair",
                            RollNumber = "R003",
                            Score = 91
                        });
                });

            modelBuilder.Entity("Academics.Api.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Designation = "Mathematics",
                            Email = "meera.iyer@school.example",
                            Name = "Meera Iyer"
                        },
                        new
                        {
                            Id = 2,
                            Designation = "Physics",
                            Email = "arjun.rao@school.example",
                            Name = "Arjun Rao"
                        });
                });

            modelBuilder.Entity("Academics.Api.Models.Course", b =>
                {
                    b.HasOne("Academics.Api.Models.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Academics.Api.Models.Enrollment", b =>
                {
                    b.HasOne("Academics.Api.Models.Course", null)
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Academics.Api.Models.Student", null)
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Academics.Api.Models.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Academics.Api.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
